- name: Collect MySQL DB info and stats
  hosts: db
  gather_facts: no
  tasks: 
    - name: Get MySQL version with non-default credentials
      mysql_info:
        login_user: pdek
        login_password: pdek
        filter: version
